### ISSUE TITLE
zhTW translation

### ISSUE THREAD

**Issue by BlueNightSky** [SacredDuckwhale/Wisent#1]
do
	local L = al:NewLocale( MAJOR, "zhTW")
	if L then 
	L.BarBuff           = "增益" 
	L.BarCombo          = "連擊"
	L.BarDebuff         = "減益"
	L.BarHidden         = "隱藏"
	L.BarName           = "按鈕條列樣貌"
	L.BarWeapon         = "武器"
	L.BarProg           = "觸發"
	L.BarSecure         = "安全"
	L.BarHijack         = "劫持"
	L.BiggerName        = "最後連擊點"
	L.BiggerDesc        = "最後的連擊點大小。."
	L.CancelAura        = [[
Wisent 取消光環 : "%s"

暴雪更改了CancelUnitBuff的調用。 現在這些功能只能通過安全按鈕的安全環境使用。 處理安全按鈕是非常有限的。 我暫時使用這個解決方法。

複製此行並將其粘貼到聊天。]]
	L.ColsDesc          = "欄數"
	L.ColsName          = "欄"
	L.CooldownDesc      = "顯示冷卻動畫。"
	L.CooldownName      = "冷卻"
	L.DebugDesc         = "顯示偵錯訊息。只有測試需要。"
	L.DebugName         = "偵錯"
	L.Description       = "所有使用者的增益，減益和武器附魔的定位和演示。"
	L.DescBuff          = "有幫助的增益"
	L.DescDebuff        = "有害的增益"
	L.DescHidden        = "已加入有幫助增益(提示)"
	L.DescProgs         = "特殊有幫助增益"
	L.DescCombos        = "連擊增益"
	L.DescMain          = "主要"
	L.DescSecure        = "安全測試"
	L.DescWeapon        = "武器附魔"
	L.EnabledDesc       = "啟用插件並隱藏暴雪標準欄。"
	L.EnabledName       = "按鈕已啟用"
	L.ForceDesc         = "強制暴雪增益框架的可見性。"
	L.ForceName         = "強制增益框架"
	L.ForceWarn         = "暴雪增益框架被其他插件停用。 您應該在其他插件上停用此選項。"
	L.FlashingDesc      = "結束時閃爍。"
	L.FlashingName      = "啟用閃爍"
	L.Help              = "幫助"
	L.HorizontalDesc    = "按鈕顯示的最初方向。"
	L.HorizontalName    = "水平優先"
	L.JoinDesc          = "加入某些特殊增益。."
	L.JoinName          = "加入增益"
	L.LBFDesc           = "啟用函數庫Buttonfacade如果存在。"
	L.LBFName           = "啟用LBF"
	L.MasqueName	= "啟用Masque"
	L.MasqueDesc = "啟用Masque的整合如果存在。"
	L.LockDesc          = "在選定位置後鎖定所有欄位。"
	L.LockName          = "按鈕樣貌"
	L.NumberDesc        = "最大可見數量的按鈕。"
	L.NumberName        = "大小"
	L.OptionName        = "共同選項"
	L.RowsDesc          = "行數"
	L.RowsName          = "行"
	L.ScaleDesc         = "按鈕的大小。"
	L.ScaleName         = "縮放"
	L.ShowDesc          = "隱藏與顯示按鈕。"
	L.ShowName          = "顯示按鈕列"
	L.SpellDesc         = "法術的ID"
	L.SpellName         = "法術ID"
	L.SortAlpha         = "名稱"
	L.SortDec           = "剩餘時間，降序"
	L.SortDesc          = "設定增益圖標的排序"
	L.SortDurationAsc   = "持續時間"
	L.SortDurationDesc  = "持續時間，降序"
	L.SortInc           = "剩餘時間"
	L.SortName          = "排序"
	L.SortNone          = "無 (暴雪順序)"
	L.SortRevert        = "名稱，降序"
	L.StyleBlizzard     = "暴雪樣式"
	L.StyleWisent1       = "短時間 (XX分)"
	L.StyleWisent2       = "總是長時間 (XX:XX)"
	L.TimerDesc         = "改變時間的樣式在Wisent或暴雪之間。"
	L.TimerName         = "計時演示"
	L.Version           = "版本"
	L.VersionDesc       = "列印當前版本。"
	L.XPaddingDesc      = "按鈕之間的水平間隔 (最小: -20, 最大: 20)。 負值改變列的方向。"
	L.XPaddingName      = "水平間隔"
	L.YPaddingDesc      = "按鈕之間的垂直間隔 (最小: -50, 最大: 50)。負值改變列的方向。"
	L.YPaddingName      = "垂直間隔"
	end
end

**Comment by rdw-software** [comment]
Thanks! I haven't worked on this for a long time, but I'll see what I can use after the localisation is updated :)

**Comment by rdw-software** [comment]
Unfortunately, most of the old localisation code had to be thrown out (as it had terrible grammar). I'm not sure if your translated phrases still match, but if so you could access the [CurseForge localisation page](https://wow.curseforge.com/projects/wisent/localization) and re-add them yourself :)

Closing this as migration of the localisation code is now complete.
