### ISSUE TITLE
Review obsolete "weapon enchants" bar

### ISSUE THREAD

**Issue by rdw-software** [SacredDuckwhale/Wisent#4]
As weapon enchants have been removed from the game, this could be either removed, or changed to only track enchant-like buffs (rogue poisons, mainly).

**Comment by rdw-software** [comment]
I guess now that weapon enchants are back, it might be worth revisiting this issue.

**Comment by thecontrarycat** [comment]
It's a simple fix.  Literally just revert the earlier commit: https://github.com/SacredDuckwhale/Wisent/commit/ec6c72cb473305494b093099f8b4f16af30e872e

**Comment by rdw-software** [comment]
Yup, pretty much. Done as of ef76b0a106d988ac061c663c3c23725828383c67, though it's possible some things have changed in how enchants are handled internally and might have to be revisited if other related issues pop up.
